# Generated by Django 3.0.4 on 2020-03-22 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RssChannel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=255, verbose_name='Link')),
                ('title', models.TextField(blank=True, default='', verbose_name='Tytuł')),
                ('description', models.TextField(blank=True, default='', verbose_name='Tekst')),
                ('last_update', models.DateTimeField(null=True, verbose_name='Ostatnia aktualizacja')),
            ],
            options={
                'verbose_name': 'Kanał RSS',
                'verbose_name_plural': 'Kanały RSS',
            },
        ),
        migrations.CreateModel(
            name='RssSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=255, verbose_name='Link')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Subskrypcja RSS',
                'verbose_name_plural': 'Subskrypcje RSS',
            },
        ),
        migrations.CreateModel(
            name='RssItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, default='', verbose_name='Tytuł')),
                ('description', models.TextField(blank=True, default='', verbose_name='Tekst')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rss_model.RssChannel')),
            ],
            options={
                'verbose_name': 'Informacja RSS',
                'verbose_name_plural': 'Informacje RSS',
            },
        ),
    ]
